---

############################
# Debug build - Only PALv1 #
############################

- friendly_name: "NSMBW: The Prankster Comets"
  short_name: 'debug'
  short_name2: 'n'
  include_dirs: ['include', 'src']
  multi_build: {
    pal: 'kamek_pal.x'
  }
  dynamic_link: true
  
###############################
# Release build - All regions #
###############################

# Non-tournaments

- friendly_name: "NSMBW: The Prankster Comets"
  short_name: 'release1'
  short_name2: 'n'
  include_dirs: ['include', 'src']
  multi_build: {
    pal: 'kamek_pal.x',
    pal2: 'kamek_pal2.x',
    ntsc: 'kamek_ntsc.x',
    ntsc2: 'kamek_ntsc2.x',
    jpn: 'kamek_jpn.x',
    jpn2: 'kamek_jpn2.x'
  }
  dynamic_link: true
  
# Tournaments (pads a few actors by two)

- friendly_name: "NSMBW: The Prankster Comets (Tournament regions)"
  short_name: 'release2'
  short_name2: 'n'
  include_dirs: ['include', 'src']
  defines: {
    'REGION_TOURNAMENT'
  }
  multi_build: {
    kor: 'kamek_kor.x',
    twn: 'kamek_twn.x'
  }
  dynamic_link: true
  
